name: Build Pull Request

on:
  push:
    branches:
    - mc/* # MC version updates
    - pr/* # PR rebases
  pull_request:
    branches:
    - 2.x
    - mc/*

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Sadge
      run: |
        echo "Sadge ${BASE}"
      env:
        BASE: ${{ $github.base.ref }}
    - name: Restore Gradle cache
      uses: actions/cache@v2.1.5
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace
    - name: Archive plugin jars on GitHub
      uses: actions/upload-artifact@master
      with:
        name: EssentialsX plugin jars
        path: jars/
